export const Types = {
  GET_PERSONS_REQUEST: "GET_PERSONS_REQUEST",
  GET_PERSONS_SUCCESS: "GET_PERSONS_SUCCESS",
  GET_PERSONS_FAILURE: "GET_PERSONS_FAILURE",

  SELECT_PERSON: "SELECT_PERSON",
  UNSELECT_PERSON: "UNSELECT_PERSON",
};
